# This workflow will install Python dependencies and lint with pylint
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pylint

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]  # PyPI publish only on version tags like v0.1.0
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: pylint .
